import type { Metadata } from 'next';
import './globals.css';
import { Toaster } from '../components/ui/toaster';
import { ReactQueryProviderComponent } from '@/providers/ReactQueryProviderComponent';
import localFont from 'next/font/local';

const generalSans = localFont({
  src: [
    {
      path: '../../public/fonts/GeneralSans-Bold.woff2',
      weight: '700'
    },
    {
      path: '../../public/fonts/GeneralSans-Regular.woff2',
      weight: '400'
    }
  ]
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={generalSans.className}>
        <ReactQueryProviderComponent>{children}</ReactQueryProviderComponent>
        <Toaster />
      </body>
    </html>
  );
}
