import './globals.css';

import type { Metadata } from 'next';
import localFont from 'next/font/local';

import { ReactQueryProviderComponent } from '@/providers/ReactQueryProviderComponent';

import pj from '../../package.json';
import { Toaster } from '../components/ui/toaster';

const generalSans = localFont({
  src: [
    {
      path: '../../public/fonts/GeneralSans-Bold.woff2',
      weight: '700'
    },
    {
      path: '../../public/fonts/GeneralSans-Semibold.woff2',
      weight: '600'
    },
    {
      path: '../../public/fonts/GeneralSans-Regular.woff2',
      weight: '400'
    }
  ]
});

export const metadata: Metadata = {
  title: 'Aquatechy',
  description: 'Generated by create next app',
  icons: [
    {
      href: '/images/favicon.ico',
      sizes: 'any',
      url: '/images/favicon.ico'
    }
  ]
};

console.log({
  env: process.env.NODE_ENV,
  version: pj.version
});

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={generalSans.className}>
        <ReactQueryProviderComponent>{children}</ReactQueryProviderComponent>
        <Toaster />
      </body>
    </html>
  );
}
